import type { Metadata } from "next";
import "./globals.css";

import Header from "../components/global/header"

export const metadata: Metadata = {
  title: "Lucrum",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="">
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
      </body>
    </html>
  );
}
